name = "PlantModules"
uuid = "c420d4a8-207b-40ca-9fc4-c574d258dc7a"
version = "0.1.0"
authors = ["Bram Spanoghe", "Michiel Stock", "Tom De Swaef"]

[deps]
GraphRecipes = "bd48cda9-67a9-57be-86fa-5b3c104eda73"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
MultiScaleTreeGraph = "dd4a991b-8a45-4075-bede-262ee62d5583"
PlantGraphs = "615ad455-9aac-4340-9247-71ef610f781a"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"

[compat]
GraphRecipes = "0.5"
Graphs = "1"
ModelingToolkit = "10"
MultiScaleTreeGraph = "0.14"
PlantGraphs = "0.0.2, 0.1"
RecipesBase = "1.3"
SciMLBase = "2.125.0"
OrdinaryDiffEq = "=6.103"
julia = "1.10"

[extras]
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Plots", "Test", "OrdinaryDiffEq"]
