[deps]
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
MultiScaleTreeGraph = "dd4a991b-8a45-4075-bede-262ee62d5583"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
PlantGraphs = "615ad455-9aac-4340-9247-71ef610f781a"
PlantModules = "c420d4a8-207b-40ca-9fc4-c574d258dc7a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Sparspak = "e56a9233-b9d6-4f03-8d0f-1825330902ac"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
