[deps]
GraphRecipes = "bd48cda9-67a9-57be-86fa-5b3c104eda73"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Memoization = "6fafb56a-5788-4b4e-91ca-c0cea6611c73"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
MultiScaleTreeGraph = "dd4a991b-8a45-4075-bede-262ee62d5583"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
PlantBiophysics = "7ae8fcfa-76ad-4ec6-9ea7-5f8f5e2d6ec9"
PlantGraphs = "615ad455-9aac-4340-9247-71ef610f781a"
PlantModules = "c420d4a8-207b-40ca-9fc4-c574d258dc7a"
PlantSimEngine = "9a576370-710b-4269-adf9-4f603a9c6423"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
