[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
PlantGraphs = "615ad455-9aac-4340-9247-71ef610f781a"
PlantModules = "c420d4a8-207b-40ca-9fc4-c574d258dc7a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
