[deps]
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
MultiScaleTreeGraph = "dd4a991b-8a45-4075-bede-262ee62d5583"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
PlantGraphs = "615ad455-9aac-4340-9247-71ef610f781a"
PlantModules = "c420d4a8-207b-40ca-9fc4-c574d258dc7a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PlutoStaticHTML = "359b1769-a58e-495b-9770-312e911026ad"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
Sparspak = "e56a9233-b9d6-4f03-8d0f-1825330902ac"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
