[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
PlantModules = "c420d4a8-207b-40ca-9fc4-c574d258dc7a"
PlutoStaticHTML = "359b1769-a58e-495b-9770-312e911026ad"
